### ISSUE TITLE
how to use your program

### ISSUE THREAD

**Issue by ayush8009** [neoranger/NeoBot#3]
how to run your program can you help me??

**Comment by neoranger** [comment]
Hi! Neobot is a Telegram Bot so you have to:
1) Create a bot in Telegram (copy the token and don't share it)
2) clone this repo
3) install pyTelegramBotAPI (`sudo pip install pytelegrambotapi`) on your PC (or where you will run the bot)
4) Config the bot with your token
5) run the bot with the script (if you are testing just run `python neobot.py`

If you have any doubt please let me know.
